Info in <TUnixSystem::ACLiC>: creating shared library /grid_mnt/vol_home/llr/cms/shatat/CMSAnalysis/eec_2b_analysis/Test_vs_Zoe_code/Zoe_version/eec_2b_analysis-main/condor/common_condor_header/run_condor_job_C.so
In file included from input_line_9:6:
In file included from /grid_mnt/vol_home/llr/cms/shatat/CMSAnalysis/eec_2b_analysis/Test_vs_Zoe_code/Zoe_version/eec_2b_analysis-main/condor/common_condor_header/run_condor_job.C:8:
/grid_mnt/vol_home/llr/cms/shatat/CMSAnalysis/eec_2b_analysis/Test_vs_Zoe_code/Zoe_version/eec_2b_analysis-main/condor/common_condor_header/create_files_for_template_fit_copy_runCodor.cpp:31:92: error: missing default argument on parameter 'applyHLT80'
                    Long64_t ev_first = 0, Long64_t ev_last = -1, Int_t job_idx = -1, bool applyHLT80) {
                                                                                           ^
/grid_mnt/vol_home/llr/cms/shatat/CMSAnalysis/eec_2b_analysis/Test_vs_Zoe_code/Zoe_version/eec_2b_analysis-main/condor/common_condor_header/create_files_for_template_fit_copy_runCodor.cpp:290:3: error: no matching function for call to 'make_templates'
  make_templates(filename, output_folder, output_hist, domain, pT_low, pT_high, n, btag, isMC, dataType, applyHLT80);
  ^~~~~~~~~~~~~~
/grid_mnt/vol_home/llr/cms/shatat/CMSAnalysis/eec_2b_analysis/Test_vs_Zoe_code/Zoe_version/eec_2b_analysis-main/condor/common_condor_header/create_files_for_template_fit_copy_runCodor.cpp:29:6: note: candidate function not viable: requires 14 arguments, but 11 were provided
void make_templates(TString filename, TString output_folder, TString output_hist, TString domain,
     ^
Error in <ACLiC>: Executing '/cvmfs/cms.cern.ch/el9_amd64_gcc12/lcg/root/6.32.13-ab9fb9ce48fa8881c07b7960f1d1b8a4/bin/rootcling -v0 "--lib-list-prefix=/grid_mnt/vol_home/llr/cms/shatat/CMSAnalysis/eec_2b_analysis/Test_vs_Zoe_code/Zoe_version/eec_2b_analysis-main/condor/common_condor_header/run_condor_job_C_ACLiC_map" -f "/grid_mnt/vol_home/llr/cms/shatat/CMSAnalysis/eec_2b_analysis/Test_vs_Zoe_code/Zoe_version/eec_2b_analysis-main/condor/common_condor_header/run_condor_job_C_ACLiC_dict.cxx" -I$ROOTSYS/include -I"/cvmfs/cms.cern.ch/el9_amd64_gcc12/lcg/root/6.32.13-ab9fb9ce48fa8881c07b7960f1d1b8a4/etc/" -I"/cvmfs/cms.cern.ch/el9_amd64_gcc12/lcg/root/6.32.13-ab9fb9ce48fa8881c07b7960f1d1b8a4/etc//cling" -I"/cvmfs/cms.cern.ch/el9_amd64_gcc12/lcg/root/6.32.13-ab9fb9ce48fa8881c07b7960f1d1b8a4/etc//cling/plugins/include" -I"/cvmfs/cms.cern.ch/el9_amd64_gcc12/lcg/root/6.32.13-ab9fb9ce48fa8881c07b7960f1d1b8a4/include/" -I"/cvmfs/cms.cern.ch/el9_amd64_gcc12/lcg/root/6.32.13-ab9fb9ce48fa8881c07b7960f1d1b8a4/include" -D__ACLIC__  "/grid_mnt/vol_home/llr/cms/shatat/CMSAnalysis/eec_2b_analysis/Test_vs_Zoe_code/Zoe_version/eec_2b_analysis-main/condor/common_condor_header/run_condor_job.C" "/grid_mnt/vol_home/llr/cms/shatat/CMSAnalysis/eec_2b_analysis/Test_vs_Zoe_code/Zoe_version/eec_2b_analysis-main/condor/common_condor_header/run_condor_job_C_ACLiC_linkdef.h"' failed!
