## Modified version to fit old ROOT 6.14 via cmsenv setup using CMSSW_10_6_36
Universe       = vanilla
Executable     = exec_jobs/job_$(Process).sh
input          = /dev/null
output         = logfiles/job_$(Cluster)_$(Process).sh.o
error          = logfiles/job_$(Cluster)_$(Process).sh.e
Log            = condor.log

getenv         = false
+SingularityImage = "/cvmfs/singularity.opensciencegrid.org/cmssw/cms:rhel7"
request_cpus   = 1
request_memory  = 2GB

WNTag          = el9
include : /opt/exp_soft/cms/t3/t3queue |


queue
